[package]
authors = ["The Rust Project Developers"]
name = "rustc_int128"
version = "0.0.0"

[lib]
name = "rustc_int128"
path = "lib.rs"
test = false

[dependencies]
serialize = { path = "../libserialize" }
